In [1]:
%pip install lxml

Collecting lxml
  Downloading lxml-6.1.0-cp312-cp312-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl.metadata (4.0 kB)
Downloading lxml-6.1.0-cp312-cp312-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl (5.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 38.1 MB/s  0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.1.0
Note: you may need to restart the kernel to use updated packages.

In [2]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 75.7 MB/s  0:00:00
Downloading numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 51.4 MB/s  0:00:006m0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.4.4 pandas-3.0.2
Note: you may need to restart the kernel to use updated packages.

In [3]:
%pip install wikipedia

Collecting wikipedia
  Downloading wikipedia-1.4.0.tar.gz (27 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: beautifulsoup4 in /home/codespace/.local/lib/python3.12/site-packages (from wikipedia) (4.14.3)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in /home/codespace/.local/lib/python3.12/site-packages (from wikipedia) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/codespace/.local/lib/python3.12/site-packages (from requests<3.0.0,>=2.0.0->wikipedia) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /home/codespace/.local/lib/python3.12/site-packages (from requests<3.0.0,>=2.0.0->wikipedia) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/codespace/.local/lib/python3.12/site-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/codespace/.local/lib/python3.12/site-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2026.2.25)
Requirement already satisfied: soupsieve>=1.6.1 in /home/codespace/.local/lib/python3.12/site-packages (from beautifulsoup4->wikipedia) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /home/codespace/.local/lib/python3.12/site-packages (from beautifulsoup4->wikipedia) (4.15.0)
Building wheels for collected packages: wikipedia
  Building wheel for wikipedia (pyproject.toml) ... done
  Created wheel for wikipedia: filename=wikipedia-1.4.0-py3-none-any.whl size=11756 sha256=30b45725bbc0763c25186bef561e45c4f9f208348dc5aaabb1874247deea229a
  Stored in directory: /home/codespace/.cache/pip/wheels/63/47/7c/a9688349aa74d228ce0a9023229c6c0ac52ca2a40fe87679b8
Successfully built wikipedia
Installing collected packages: wikipedia
Successfully installed wikipedia-1.4.0
Note: you may need to restart the kernel to use updated packages.

In [4]:
%pip install wget

Collecting wget
  Downloading wget-3.2.zip (10 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: wget
  Building wheel for wget (pyproject.toml) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9685 sha256=38b4f1ae346da818606192a0ac26aea5bd07f0005b4aafc7e55fc922e0a0e7da
  Stored in directory: /home/codespace/.cache/pip/wheels/01/46/3b/e29ffbe4ebe614ff224bad40fc6a5773a67a163251585a13a9
Successfully built wget
Installing collected packages: wget
Successfully installed wget-3.2
Note: you may need to restart the kernel to use updated packages.

In [5]:
import pandas as pd
import wikipedia
import wget
import io

In [6]:
%xmode Minimal
wiki_tables=pd.read_html('https://en.wikipedia.org/wiki/Northern_Sea_Route')

Exception reporting mode: Minimal

HTTPError: HTTP Error 403: Forbidden

In [7]:
wiki_page=wikipedia.page('Northern_Sea_Route',auto_suggest = False).html()

In [8]:
wiki_tables2=pd.read_html(io.StringIO(wiki_page))

In [9]:
wiki_tables2[0]

,Year,Total,Russia,Singapore,Finland,Norway,Germany,Spain,China,Greece,Hong Kong,Sweden,Netherlands,Portugal,Other
0,2007,2,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2008,3,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2009,5,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010,10,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2011,41,26.0,4.0,2.0,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,5.0
5,2012,46,18.0,NaN,6.0,5.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,15.0
6,2013,71,46.0,NaN,2.0,2.0,NaN,NaN,NaN,2.0,1.0,NaN,NaN,NaN,18.0
7,2014,53,47.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,3.0
8,2015,18,10.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,1.0,1.0,NaN,4.0
9,2016,18,7.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,8.0
10,2017,27,9.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,3.0,NaN,2.0,1.0,10.0
11,2018,27,8.0,NaN,1.0,NaN,NaN,NaN,7.0,NaN,1.0,NaN,1.0,2.0,6.0
12,2019,37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2020,64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2021,85,12.0,NaN,4.0,NaN,NaN,NaN,11.0,NaN,7.0,NaN,8.0,13.0,30.0
15,2022,43,36.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0

In [10]:
wiki_DOP=wikipedia.page("Dilution_of_precision_(navigation)")

In [11]:
wiki_DOP.images

['https://upload.wikimedia.org/wikipedia/commons/c/c3/Bad_gdop.png',
 'https://upload.wikimedia.org/wikipedia/commons/7/7b/Geometric_Dilution_Of_Precision.svg',
 'https://upload.wikimedia.org/wikipedia/commons/9/95/Good_gdop.png']

In [12]:
wget.download(wiki_DOP.images[1])

HTTPError: HTTP Error 403: Forbidden

For context see this blog post https://diff.wikimedia.org/2026/03/26/quo-vadis-crawlers-progress-and-whats-next-on-safeguarding-our-infrastructure/

In [13]:
wiki_table=wiki_tables2[0]

In [14]:
wiki_table['Hong Kong']

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
5     NaN
6     1.0
7     NaN
8     NaN
9     2.0
10    3.0
11    1.0
12    NaN
13    NaN
14    7.0
15    NaN
Name: Hong Kong, dtype: float64

In [15]:
wiki_table.set_index('Year').loc[2013].to_dict()

{'Total': 71.0,
 'Russia': 46.0,
 'Singapore': nan,
 'Finland': 2.0,
 'Norway': 2.0,
 'Germany': nan,
 'Spain': nan,
 'China': nan,
 'Greece': 2.0,
 'Hong Kong': 1.0,
 'Sweden': nan,
 'Netherlands': nan,
 'Portugal': nan,
 'Other': 18.0}

In [16]:
wiki_page=wikipedia.page('List_of_airports_by_IATA_airport_code:_A',auto_suggest = False)

In [17]:
file_dump=open('wiki_file2_dump.html','w')
file_dump.write(wiki_page.html())
file_dump.close()

In [18]:
wiki_table_problem=pd.read_html(io.StringIO(wiki_page.html()))

In [19]:
problem_table=wiki_table_problem[0]

In [25]:
problem_table.iloc[550:]

,IATA,ICAO,Airport name,Location served,Time,DST
,-AA-,-AA-,-AA-,-AA-,-AA-,-AA-
550,AZL,SWTU[4],Fazenda Tucunaré Airport[1],"Sapezal, Mato Grosso, Brazil",UTC−04:00,NaN
551,AZN,UTFA,Andizhan Airport,"Andizhan, Uzbekistan",UTC+05:00,NaN
552,AZO,KAZO,Kalamazoo/Battle Creek International Airport,"Kalamazoo, Michigan, United States",UTC−05:00,Mar-Nov
553,AZP,MMJC,Jorge Jiménez Cantú National Airport,"Ciudad López Mateos, State of Mexico, Mexico",UTC−06:00,Apr-Oct
554,AZR,DAUA,Touat-Cheikh Sidi Mohamed Belkebir Airport,"Adrar, Algeria",UTC+01:00,NaN
555,AZS,MDCY,Samaná El Catey International Airport,"El Catey, Dominican Republic",UTC−04:00,NaN
556,AZT,NaN,Zapatoca Airport,"Zapatoca, Colombia",UTC−05:00,NaN
557,AZZ,FNAM,Ambriz Airport,"Ambriz, Angola",UTC+01:00,NaN

In [28]:
problem_table

,IATA,ICAO,Airport name,Location served,Time,DST
,-AA-,-AA-,-AA-,-AA-,-AA-,-AA-
0,AAA,NTGA,Anaa Airport,"Anaa, Tuamotus, French Polynesia",UTC−10:00,NaN
1,AAB,YARY,Arrabury Airport,"Arrabury, Queensland, Australia",UTC+10:00,NaN
2,AAC,HEAR,El Arish International Airport,"El Arish, Egypt",UTC+02:00,NaN
3,AAD,HCAD,Adado Airport,"Adado (Cadaado), Galguduud, Somalia",UTC+03:00,NaN
4,AAE,DABB,Rabah Bitat Airport (Les Salines Airport),"Annaba, Algeria",UTC+01:00,NaN
...,...,...,...,...,...,...
553,AZP,MMJC,Jorge Jiménez Cantú National Airport,"Ciudad López Mateos, State of Mexico, Mexico",UTC−06:00,Apr-Oct
554,AZR,DAUA,Touat-Cheikh Sidi Mohamed Belkebir Airport,"Adrar, Algeria",UTC+01:00,NaN
555,AZS,MDCY,Samaná El Catey International Airport,"El Catey, Dominican Republic",UTC−04:00,NaN
556,AZT,NaN,Zapatoca Airport,"Zapatoca, Colombia",UTC−05:00,NaN
557,AZZ,FNAM,Ambriz Airport,"Ambriz, Angola",UTC+01:00,NaN

In [26]:
problem_table["Airport name"]

KeyError: 'Airport name'

In [27]:
problem_table.iloc[1].to_dict()

{('IATA', '-AA-'): 'AAB',
 ('ICAO', '-AA-'): 'YARY',
 ('Airport\xa0name', '-AA-'): 'Arrabury Airport',
 ('Location\xa0served', '-AA-'): 'Arrabury, Queensland, Australia',
 ('Time', '-AA-'): 'UTC+10:00',
 ('DST', '-AA-'): nan}

in html it looks like
```html
<th style="text-align:left;">Airport&#160;name
</th>
<th style="text-align:left;">Location&#160;served
</th>
```

In [29]:
chr(160)

'\xa0'

In [30]:
problem_table["Airport\xa0name"]

                                           -AA-
0                                  Anaa Airport
1                              Arrabury Airport
2                El Arish International Airport
3                                 Adado Airport
4     Rabah Bitat Airport (Les Salines Airport)
..                                          ...
553        Jorge Jiménez Cantú National Airport
554  Touat-Cheikh Sidi Mohamed Belkebir Airport
555       Samaná El Catey International Airport
556                            Zapatoca Airport
557                              Ambriz Airport

[558 rows x 1 columns]

Ugly but it works

In [31]:
problem_table.to_csv('problem_table.csv')

In [32]:
problem_table_from_file=pd.read_csv('problem_table.csv')

In [37]:
problem_table_from_file["Airport name"]

KeyError: 'Airport name'

In [36]:
problem_table_from_file.iloc[1].to_dict()#

{'Unnamed: 0': 0.0,
 'IATA': 'AAA',
 'ICAO': 'NTGA',
 'Airport\xa0name': 'Anaa Airport',
 'Location\xa0served': 'Anaa, Tuamotus, French Polynesia',
 'Time': 'UTC−10:00',
 'DST': nan}